- name: Deploy Maven Artifact
  hosts: web
  become: yes

  tasks:

  - name: Create deployment directory
    file:
      path: /opt/deploy/batch1
      state: directory
      mode: '0755'

  - name: Copy artifact
    copy:
      src: target/demo-app-1.0-SNAPSHOT.jar
      dest: /opt/deploy/batch1/demo-app.jar

